/** Chữ đối soát (D15) + điều chỉnh trạng thái kho (D4 / D15) — nguyên văn 01 §10.5 khi có (02b-admin §9). */
export const COPY = {
  adjust: {
    open: "Điều chỉnh trạng thái",
    title: "Điều chỉnh trạng thái",
    current: "Trạng thái hiện tại",
    target: "Trạng thái đích",
    reason: "Lý do",
    reasonHint: "Bắt buộc, 5–500 ký tự",
    reasonRule: "Nhập lý do 5–500 ký tự.",
    targetRequired: "Chọn trạng thái đích.",
    submit: "Xác nhận",
    done: "Đã điều chỉnh trạng thái kho.",
    noTargets: "Không còn chuyển trạng thái nào được phép cho kiện này.",
  },
  /** D15 — Lệch trạng thái (01 §10.5 D15). */
  list: {
    title: "Lệch trạng thái",
    subtitle: "Kiện có trạng thái kho và trạng thái sàn không khớp",
    tabs: "Trạng thái cảnh báo",
    tab: { OPEN: "Đang mở", RESOLVED: "Đã xử lý", ALL: "Tất cả" },
    caption: "Danh sách cảnh báo lệch trạng thái",
    results: "Kết quả",
    severity: "Mức",
    rule: "Quy tắc",
    any: "Tất cả",
    from: "Từ",
    to: "Đến",
    clear: "Xóa bộ lọc",
    loading: "Đang tải cảnh báo",
    error: "Không tải được danh sách cảnh báo.",
    retry: "Thử lại",
    rangeError: "Khoảng ngày không hợp lệ (tối đa 92 ngày).",
    empty: "Không có lệch trạng thái nào đang mở.",
    emptyOther: "Chưa có cảnh báo nào.",
    emptyFiltered: "Không có cảnh báo nào khớp bộ lọc.",
    col: {
      severity: "Mức",
      rule: "Quy tắc",
      package: "Mã kiện",
      warehouse: "Kho",
      platform: "Sàn",
      since: "Từ lúc",
      result: "Kết quả xử lý",
      actions: "Thao tác",
    },
    resolve: "Xử lý",
    resolveFor: (code: string) => `Xử lý cảnh báo kiện ${code}`,
    run: "Chạy đối soát ngay",
    runQueued: "Đã yêu cầu chạy đối soát. Danh sách tự cập nhật khi xong.",
    runBusy: "Đối soát đang chạy.",
    by: (who: string, at: string) => `${who} · ${at}`,
    autoResolved: (at: string) => `Tự hết ${at}`,
    action: {
      RESOLVE: "Đánh dấu đã xử lý",
      ADJUST_STATUS: "Điều chỉnh trạng thái kho",
      OPEN_CLAIM: "Tạo hồ sơ khiếu nại",
    },
  },
  /** Dialog "Xử lý cảnh báo" (01 §10.5 D15). */
  resolve: {
    title: "Xử lý cảnh báo",
    package: "Kiện",
    warehouse: "Trạng thái kho",
    platform: "Trạng thái sàn",
    since: "Từ lúc",
    openPackage: "Mở chi tiết kiện",
    history: "Lịch sử gần nhất",
    historyLoading: "Đang tải lịch sử",
    noHistory: "Chưa có lịch sử trạng thái.",
    actions: "Hành động",
    note: "Ghi chú",
    noteHint: "Bắt buộc, tối đa 500 ký tự",
    noteRule: "Nhập ghi chú 1–500 ký tự.",
    submit: "Xác nhận",
    done: "Đã xử lý cảnh báo.",
    /** 409 ALREADY_RESOLVED (01 §10.5 D15 "Xung đột"). */
    resolvedBy: (who: string, at: string) => `Cảnh báo này đã được ${who} xử lý lúc ${at}.`,
    autoResolved: (at: string) => `Cảnh báo này đã tự hết lúc ${at}.`,
  },
  generic: "Có lỗi hệ thống. Thử lại sau ít phút.",
};
