import { fmtDate } from "@/shared/format";

/** Chữ D3, D4, dialog xuất — nguyên văn 01 §10.5 khi có (DEC-17). */
export const COPY = {
  search: {
    title: "Tra cứu đơn",
    subtitle: "Quét hoặc nhập mã vận đơn, mã đơn sàn; lọc theo ngày, station, trạng thái",
    q: "Mã vận đơn hoặc mã đơn",
    qHint: "Quét mã bằng máy quét hoặc gõ rồi bấm Enter",
    from: "Từ ngày",
    to: "Đến ngày",
    station: "Station",
    warehouse: "Trạng thái kho",
    source: "Nguồn",
    all: "Tất cả",
    submit: "Tìm",
    clear: "Xóa bộ lọc",
    sessionFilter: "Lọc theo phiên",
    removeSessionFilter: (label: string) => `Bỏ lọc ${label}`,
    notFoundCode: (q: string) => `Không tìm thấy mã ${q}.`,
    notFound: "Không tìm thấy kiện nào khớp bộ lọc.",
    error: "Không tải được danh sách kiện.",
    retry: "Thử lại",
  },
  col: {
    tracking: "Mã vận đơn",
    order: "Mã đơn",
    warehouse: "Trạng thái kho",
    platform: "Trạng thái sàn",
    station: "Station",
    packedAt: "Giờ đóng gói",
    clip: "Clip",
  },
  detail: {
    notFound: "Không tìm thấy kiện.",
    back: "Về Tra cứu đơn",
    error: "Không tải được thông tin kiện.",
    noSession: "Kiện này chưa được đóng gói.",
    openSession: "Phiên đang mở. Clip có sau khi phiên kết thúc.",
    orderSn: "Mã đơn",
    source: "Nguồn",
    note: "Ghi chú",
    clip: "Clip",
    sessions: "Phiên",
    items: "Sản phẩm",
    noItems: "Chưa có danh sách sản phẩm cho đơn này.",
    timeline: "Dòng thời gian",
    cam2Match: "Cam 2: khớp mã",
    rebuildOk: "Đang cắt lại clip. Clip sẵn sàng trong khoảng 1 phút.",
    notFailed: "Clip không ở trạng thái lỗi.",
    rebuild: "Thử lại",
    copy: "Copy",
    copied: "Đã copy",
    copyHash: (role: string) => `Copy SHA-256 ${role}`,
    export: "Xuất clip",
    unverified: "Chưa xác minh với Shopee",
    warehouse: "Kho",
    platform: "Shopee",
    placeholder: "Kiện tạm",
    operator: (name: string) => `Người kiểm ${name}`,
    packSnapshot: "Ảnh lúc đóng gói",
    claims: "Hồ sơ khiếu nại",
    noClaims: "Kiện này chưa có hồ sơ khiếu nại.",
    openClaim: "Mở",
    recon: "Cảnh báo lệch",
    reconLink: "Xem ở Lệch trạng thái",
    returnDone: "Đã kiểm xong",
  },
  /** Chip bảo vệ clip (01 §10.5 D4 "Bỏ Giữ clip", FR-02.06, 02.09). */
  protection: {
    label: "Bảo vệ clip",
    claim: (code: string) => `Đang được giữ: hồ sơ khiếu nại ${code}`,
    returnCase: (code: string) => `Đang được giữ: hàng hoàn ${code}`,
    until: (date: string) => `tới ${date}`,
    held: "Đang được giữ: Admin giữ clip",
    hint: "Muốn giữ clip? Tạo hồ sơ khiếu nại.",
  },
  exportDialog: {
    title: "Xuất clip",
    layout: "Chọn camera",
    layouts: { CAM1: "Cam 1", CAM2: "Cam 2", SIDE_BY_SIDE: "Ghép" },
    hint: "File MP4 có overlay mã vận đơn, mã đơn, thời gian và tên station.",
    create: "Tạo file xuất",
    progress: "Đang tạo file xuất",
    ready: "File xuất đã sẵn sàng.",
    video: "Tải file MP4",
    info: "Tải thông tin (JSON)",
    failed: "Không tạo được file xuất. Bấm Thử lại; nếu vẫn lỗi, báo Admin kèm mã đơn.",
    retry: "Thử lại",
    notReady: "Clip đang được cắt, sẵn sàng trong khoảng 1 phút.",
    deleted: "Clip đã bị xóa theo chính sách lưu trữ, không xuất được.",
    deletedOn: (date: string, days: number | null) =>
      `Clip đã bị xóa ngày ${fmtDate(date)} theo chính sách lưu trữ${days ? ` ${days} ngày` : ""}, không xuất được.`,
    clipFailed: "Clip cắt lỗi — Admin/Supervisor có thể cắt lại rồi xuất.",
    gone: "Bản xuất không còn (quá 24 giờ hoặc do tài khoản khác tạo). Chọn camera rồi bấm Tạo file xuất.",
    generic: "Có lỗi hệ thống. Thử lại sau ít phút.",
    expires: "Liên kết tải hết hạn lúc",
  },
  generic: "Có lỗi hệ thống. Thử lại sau ít phút.",
  hasClip: "Có clip",
  noClip: "Chưa có clip",
  validate: {
    q: "Tối đa 64 ký tự.",
    range: "Ngày đến phải sau hoặc bằng ngày từ.",
    max: "Khoảng ngày tối đa 92 ngày.",
  },
};
