/** Chữ D8 — nguyên văn 01 §10.5 khi có (DEC-17). */
export const COPY = {
  title: "Lưu trữ video",
  subtitle: "Số ngày giữ video, ngưỡng thời gian phiên và tình trạng hệ thống",
  retentionTitle: "Thời gian lưu",
  sessionTitle: "Ngưỡng thời gian phiên",
  thresholdTitle: "Ngưỡng hàng hoàn, đối soát, hồ sơ",
  field: {
    retention_raw_days: "Số ngày giữ video thô",
    retention_clip_days: "Số ngày giữ clip",
    session_warn_minutes: "Cảnh báo khi phiên quá (phút)",
    session_abandon_minutes: "Bỏ dở phiên sau (phút)",
    // item 02 (01 §10.5 D8 "Ngưỡng mới").
    return_missing_days: "Hàng hoàn chưa về sau (ngày)",
    handover_warn_hours: "Kiện đóng xong chưa bàn giao sau (giờ)",
    claim_deadline_days: "Hạn khiếu nại mặc định (ngày)",
    claim_due_soon_hours: "Báo sắp hết hạn trước (giờ)",
    return_warn_minutes: "Phiên hoàn: cảnh báo sau (phút)",
    return_abandon_minutes: "Phiên hoàn: tự đóng sau (phút)",
  },
  hint: {
    retention_raw_days: "Video ghi liên tục của camera. 1–365 ngày.",
    retention_clip_days: "Clip của từng phiên; clip gắn hồ sơ khiếu nại / hàng hoàn chưa xong không bị xóa.",
    session_warn_minutes: "Station hiện cảnh báo khi phiên mở lâu hơn. 1–1440 phút.",
    session_abandon_minutes: "Phiên tự chuyển Bỏ dở sau thời gian này. 1–1440 phút.",
    return_missing_days: "Quá số ngày này kiện hoàn chuyển Quá hạn + cảnh báo Cao. 1–60 ngày.",
    handover_warn_hours: "Kiện đã đóng gói quá số giờ này mà chưa bàn giao → cảnh báo. 1–168 giờ.",
    claim_deadline_days: "Hạn gửi khiếu nại khi sàn không báo hạn. 1–90 ngày.",
    claim_due_soon_hours: "Hồ sơ còn ít hơn số giờ này tới hạn → tô đỏ, báo sắp hết hạn. 1–168 giờ.",
    return_warn_minutes: "Station nhận hoàn cảnh báo khi phiên mở lâu hơn. 1–1440 phút.",
    return_abandon_minutes: "Phiên hoàn tự đóng sau thời gian này. 1–1440 phút.",
  },
  /** 01 §10.5 D8: "Tối thiểu 60 ngày (cấu hình máy chủ)". */
  minClip: (min: number) => `Tối thiểu ${min} ngày (cấu hình máy chủ).`,
  belowMin: (min: number) => `Số ngày giữ clip không được thấp hơn ${min}.`,
  days: "Nhập số ngày từ 1 đến 365.",
  minutes: "Nhập số phút từ 1 đến 1440.",
  range: (max: number) => `Nhập số từ 1 đến ${max}.`,
  clipLtRaw: "Số ngày giữ clip phải lớn hơn hoặc bằng video thô.",
  abandonLteWarn: "Thời gian bỏ dở phải lớn hơn thời gian cảnh báo.",
  returnAbandonLteWarn: "Thời gian tự đóng phải lớn hơn thời gian cảnh báo.",
  /** Dialog xác nhận hạ retention (01 §10.5 D8, BR-25). */
  reduce: {
    title: "Giảm thời gian lưu?",
    loading: "Đang tính số clip bị ảnh hưởng",
    body: (at: string, clips: string, size: string, hours: string) =>
      `Lần dọn tự động lúc ${at} sẽ xóa ${clips} clip (≈ ${size}) và ${hours} giờ video thô.`,
    protected: "Clip gắn hồ sơ khiếu nại đang mở không bị xóa.",
    protectedCount: (n: string) => `${n} clip đang được bảo vệ sẽ được giữ lại.`,
    error: "Không tính được số clip bị ảnh hưởng. Thử lại.",
    retry: "Thử lại",
    confirm: "Giảm và lưu",
    cancel: "Hủy",
  },
  save: "Lưu",
  saved: "Đã lưu.",
  reset: "Hoàn tác",
  loadError: "Không tải được cài đặt.",
  retry: "Thử lại",
  generic: "Có lỗi hệ thống. Thử lại sau ít phút.",
  health: {
    title: "Sức khỏe hệ thống",
    loadError: "Không tải được tình trạng hệ thống.",
    disk: "Ổ lưu video",
    diskUsed: (used: string, total: string, pct: number) => `Đã dùng ${used} / ${total} (${pct}%)`,
    diskUnknown: "Không đọc được dung lượng ổ.",
    diskWarn: (pct: number) =>
      `Ổ lưu video đã dùng ${pct}%. Giảm số ngày giữ video thô hoặc thêm ổ trước khi đầy.`,
    services: "Dịch vụ",
    db: "Cơ sở dữ liệu",
    redis: "Redis",
    mediamtx: "Máy chủ video (MediaMTX)",
    ok: "Hoạt động",
    error: "Lỗi",
    cameras: "Camera",
    noCameras: "Chưa có camera nào.",
    online: "Online",
    offline: "Mất tín hiệu",
    offset: (ms: number) => `Lệch giờ ${ms} ms`,
    noOffset: "Chưa đo lệch giờ",
    sync: "Đồng bộ Shopee",
    noSync: "Chưa kết nối shop nào.",
    lastSuccess: (at: string) => `Thành công gần nhất ${at}`,
    syncError: "Có lỗi đồng bộ — xem Kết nối sàn.",
    refresh: "Tự làm mới mỗi 30 giây",
  },
};
