/** Chữ D8 — nguyên văn 01 §10.5 khi có (DEC-17). */
export const COPY = {
  title: "Lưu trữ video",
  subtitle: "Số ngày giữ video, ngưỡng thời gian phiên và tình trạng hệ thống",
  retentionTitle: "Thời gian lưu",
  sessionTitle: "Ngưỡng thời gian phiên",
  field: {
    retention_raw_days: "Số ngày giữ video thô",
    retention_clip_days: "Số ngày giữ clip",
    session_warn_minutes: "Cảnh báo khi phiên quá (phút)",
    session_abandon_minutes: "Bỏ dở phiên sau (phút)",
  },
  hint: {
    retention_raw_days: "Video ghi liên tục của camera. 1–365 ngày.",
    retention_clip_days: "Clip của từng phiên đóng gói; clip đang giữ không bị xóa. 1–365 ngày.",
    session_warn_minutes: "Station hiện cảnh báo khi phiên mở lâu hơn. 1–1440 phút.",
    session_abandon_minutes: "Phiên tự chuyển Bỏ dở sau thời gian này. 1–1440 phút.",
  },
  days: "Nhập số ngày từ 1 đến 365.",
  minutes: "Nhập số phút từ 1 đến 1440.",
  clipLtRaw: "Số ngày giữ clip phải lớn hơn hoặc bằng video thô.",
  abandonLteWarn: "Thời gian bỏ dở phải lớn hơn thời gian cảnh báo.",
  save: "Lưu",
  saved: "Đã lưu.",
  reset: "Hoàn tác",
  loadError: "Không tải được cài đặt.",
  retry: "Thử lại",
  generic: "Có lỗi hệ thống. Thử lại sau ít phút.",
  health: {
    title: "Sức khỏe hệ thống",
    loadError: "Không tải được tình trạng hệ thống.",
    disk: "Ổ lưu video",
    diskUsed: (used: string, total: string, pct: number) => `Đã dùng ${used} / ${total} (${pct}%)`,
    diskUnknown: "Không đọc được dung lượng ổ.",
    diskWarn: (pct: number) =>
      `Ổ lưu video đã dùng ${pct}%. Giảm số ngày giữ video thô hoặc thêm ổ trước khi đầy.`,
    services: "Dịch vụ",
    db: "Cơ sở dữ liệu",
    redis: "Redis",
    mediamtx: "Máy chủ video (MediaMTX)",
    ok: "Hoạt động",
    error: "Lỗi",
    cameras: "Camera",
    noCameras: "Chưa có camera nào.",
    online: "Online",
    offline: "Mất tín hiệu",
    offset: (ms: number) => `Lệch giờ ${ms} ms`,
    noOffset: "Chưa đo lệch giờ",
    sync: "Đồng bộ Shopee",
    noSync: "Chưa kết nối shop nào.",
    lastSuccess: (at: string) => `Thành công gần nhất ${at}`,
    syncError: "Có lỗi đồng bộ — xem Kết nối Shopee.",
    refresh: "Tự làm mới mỗi 30 giây",
  },
};
