/** Chữ D9 — nguyên văn 01 §10.5 / 02 §6 khi có (DEC-17). */
export const COPY = {
  title: "Người dùng",
  subtitle: "Tài khoản dashboard và tài khoản station",
  add: "Thêm người dùng",
  roleFilter: "Vai trò",
  allRoles: "Tất cả vai trò",
  empty: "Chưa có tài khoản nào.",
  emptyFiltered: "Không có tài khoản nào với vai trò này.",
  loadError: "Không tải được danh sách người dùng.",
  retry: "Thử lại",
  col: {
    name: "Tên",
    username: "Tài khoản",
    role: "Vai trò",
    station: "Station gắn với",
    status: "Trạng thái",
  },
  active: "Đang hoạt động",
  locked: "Đã khóa",
  noStation: "Chưa gắn station",
  action: {
    edit: (n: string) => `Sửa ${n}`,
    password: (n: string) => `Đặt lại mật khẩu ${n}`,
    lock: (n: string) => `Khóa tài khoản ${n}`,
    unlock: (n: string) => `Mở khóa ${n}`,
    revoke: (n: string) => `Thu hồi phiên đăng nhập ${n}`,
  },
  form: {
    createTitle: "Thêm người dùng",
    editTitle: "Sửa người dùng",
    username: "Tên đăng nhập",
    usernameHint: "3–32 ký tự: chữ thường không dấu, số, dấu . _ -",
    usernameInvalid: "Tên đăng nhập 3–32 ký tự, chỉ gồm chữ thường không dấu, số và . _ -",
    usernameTaken: "Tên đăng nhập đã tồn tại.",
    displayName: "Tên hiển thị",
    displayNameRequired: "Nhập tên hiển thị (tối đa 80 ký tự).",
    role: "Vai trò",
    password: "Mật khẩu",
    newPassword: "Mật khẩu mới",
    passwordHint: "Ít nhất 8 ký tự",
    passwordShort: "Mật khẩu phải có ít nhất 8 ký tự.",
    stationHint: "Gắn tài khoản station với bàn đóng gói ở mục Station.",
    roleChangeHint: "Đổi vai trò sẽ đăng xuất tài khoản này khỏi mọi thiết bị.",
    create: "Tạo tài khoản",
    save: "Lưu",
  },
  lastAdmin: "Phải còn ít nhất một Admin.",
  lockTitle: "Khóa tài khoản?",
  lockBody: (n: string) =>
    `${n} sẽ không đăng nhập được và bị đăng xuất khỏi mọi thiết bị. Mở khóa lại được bất cứ lúc nào.`,
  lockConfirm: "Khóa tài khoản",
  passwordTitle: "Đặt lại mật khẩu",
  passwordBody: (n: string) =>
    `Đặt mật khẩu mới cho ${n}. Tài khoản sẽ phải đăng nhập lại trên mọi thiết bị.`,
  passwordConfirm: "Đặt mật khẩu",
  revokeTitle: "Thu hồi phiên đăng nhập?",
  revokeBody: (n: string) =>
    `${n} sẽ phải đăng nhập lại. Máy station đang mở có thể chạy tiếp tối đa 15 phút trước khi về màn đăng nhập.`,
  revokeConfirm: "Thu hồi",
  toast: {
    created: "Đã tạo tài khoản.",
    saved: "Đã lưu.",
    locked: "Đã khóa tài khoản.",
    unlocked: "Đã mở khóa tài khoản.",
    password: "Đã đặt lại mật khẩu. Tài khoản phải đăng nhập lại.",
    revoked: "Đã thu hồi phiên đăng nhập. Station về màn đăng nhập trong tối đa 15 phút.",
  },
  generic: "Có lỗi hệ thống. Thử lại sau ít phút.",
};
