import { fmtDate, fmtDuration, fmtShort } from "@/shared/format";

/** Chữ ShareLinkDialog — nguyên văn 01 §10.5 "ShareLinkDialog" (DEC-17). */
export const COPY = {
  open: "Tạo link chia sẻ",
  openFor: (label: string) => `Tạo link chia sẻ ${label}`,
  title: "Tạo link chia sẻ bằng chứng",
  headerClaim: (claim: string, tracking: string) => `Hồ sơ ${claim} · Kiện ${tracking}`,
  headerSession: (tracking: string) => `Kiện ${tracking}`,
  sessions: (max: number) => `Phiên gửi kèm (tối đa ${max})`,
  pack: "Đóng gói",
  ret: "Mở hoàn",
  prior: "phiên trước",
  primary: "Phiên chính",
  review: "Cần soát",
  unavailable: {
    CLIP_PENDING: () => "Chưa có clip",
    CLIP_FAILED: () => "Clip lỗi",
    CLIP_DELETED: (at: string | null) =>
      at ? `Clip đã bị xóa ngày ${fmtShort(at).slice(0, 5)}` : "Clip đã bị xóa",
    CLIP_MISSING: () => "Clip thiếu tệp",
  },
  layout: "Góc quay",
  snapshots: (n: number) => `Kèm ảnh (${n})`,
  recipient: "Gửi cho *",
  recipientHint: "Ví dụ: CSKH Shopee – phiếu 98765",
  expires: "Hết hạn sau",
  days: (n: number) => `${n} ngày`,
  privacy:
    "Video Cam 2 có thể thấy nhãn vận đơn (tên, SĐT người mua). Chỉ gửi link cho sàn / ĐVVC của đơn này.",
  cancel: "Hủy",
  create: "Tạo link",
  noSessions: "Chưa có phiên nào có clip.",
  loadError: "Không tải được danh sách phiên.",
  retry: "Thử lại",
  minSessions: "Chọn ít nhất 1 phiên.",
  maxSessions: "Chọn tối đa 4 phiên.",
  maxDuration: "Tổng thời lượng tối đa 30 phút.",
  recipientRule: "Ghi rõ gửi cho ai (3–100 ký tự).",
  cloudMissing: "Chưa cấu hình kho lưu cloud. Admin: Cài đặt → Sao lưu.",
  reviewPending: (n: number) =>
    `Hồ sơ còn ${n} phiên mở hoàn Cần soát chưa xử lý — xem ở chi tiết hồ sơ trước khi gửi link.`,
  noOpeningVideo: "Chưa chọn video mở hộp nào — link chỉ có video đóng gói.",
  progress: "Tiến độ tạo link",
  rendering: (i: number, n: number) => `Đang dựng video (${i}/${n})…`,
  uploading: "Đang tải lên…",
  close: "Đóng",
  background: "Link tiếp tục được tạo khi đóng. Kết quả có ở Link chia sẻ.",
  ready: "Link đã sẵn sàng",
  linkLabel: "Link chia sẻ",
  copy: "Sao chép link",
  copied: "Đã sao chép link.",
  expiresAt: (at: string) => `Hết hạn ${fmtDate(at)} ${fmtShort(at).slice(6)}`,
  sentTo: (r: string) => `Gửi cho: ${r}`,
  uploadFailed: "Không tải được lên kho lưu cloud. Kiểm tra Internet rồi bấm Thử lại.",
  renderFailed: "Không dựng được video. Bấm Thử lại; nếu vẫn lỗi, báo Admin kèm mã hồ sơ.",
  doneToast: (r: string) => `Link chia sẻ cho "${r}" đã sẵn sàng.`,
  failedToast: (r: string) => `Không tạo được link chia sẻ cho "${r}". Mở Link chia sẻ để xem lỗi.`,
  duration: (s: number) => fmtDuration(s),
};
