/** Chữ khối "Hàng hoàn" ở D4 + Dialog Gắn đơn / Sửa kết luận — nguyên văn 01 §10.5 D4 khi có (02b-admin §9). */
export const COPY = {
  section: {
    title: "Hàng hoàn",
    request: (sn: string) => `Yêu cầu ${sn}`,
    returnTracking: "Mã chiều về",
    reason: "Lý do",
    reported: "Sàn báo",
    due: "Hạn phản hồi",
    packages: (n: number) => `${n} kiện`,
    claims: "Hồ sơ khiếu nại",
    photos: "Ảnh",
    noInspection: "Chưa có kết quả kiểm.",
    mergedInto: (code: string) => `Đã gộp vào ${code}`,
  },
  inspection: {
    result: "Kết quả kiểm",
    operator: (name: string) => `Người kiểm ${name}`,
    product: "Sản phẩm",
    requested: "Yêu cầu",
    received: "Nhận",
    condition: "Tình trạng",
    reference: "Chỉ tham khảo",
    autoClosed: "Tự đóng",
    corrected: (n: number) => `Đã sửa ${n} lần`,
    history: "Lịch sử sửa kết luận",
    before: "Kết luận trước",
    reason: "Lý do",
    note: "Ghi chú",
    noLines: "Không có dòng sản phẩm.",
  },
  link: {
    open: "Gắn đơn",
    title: "Gắn đơn",
    code: "Mã đơn sàn hoặc mã vận đơn gốc",
    codeHint: "Nhập rồi bấm Tìm",
    min: "Nhập ít nhất 6 ký tự.",
    find: "Tìm",
    searching: "Đang tìm đơn",
    notFound: "Không tìm thấy đơn.",
    pick: "Chọn kiện",
    preview: "Đơn tìm được",
    order: (sn: string) => `Đơn ${sn}`,
    mergeInto: (code: string) => `Sẽ gộp vào ${code}`,
    submit: "Gắn đơn này",
    done: (sn: string) => `Đã gắn đơn ${sn}.`,
    mergedClaim: (from: string, into: string) => `Đã gộp ${from} vào ${into}`,
    alreadyReturned: "Đơn này đã có kiện hoàn được nhận.",
  },
  correct: {
    open: "Sửa kết luận",
    title: "Sửa kết luận",
    expired: "Đã quá 7 ngày, không sửa được.",
    applyAll: (n: number, code: string) => `Áp cho cả ${n} kiện của hồ sơ ${code}`,
    reference: "Đơn nhiều kiện — dòng sản phẩm chỉ tham khảo, chỉ sửa kết luận chung.",
    received: (name: string) => `Số nhận ${name}`,
    condition: (name: string) => `Tình trạng ${name}`,
    conclusion: "Kết luận",
    okLocked: "Có dòng thiếu / hỏng — không chọn Nguyên vẹn được.",
    note: "Ghi chú",
    noteRequired: "Nhập ghi chú khi chọn Khác.",
    noteMax: "Tối đa 500 ký tự.",
    reason: "Lý do sửa",
    reasonHint: "Bắt buộc, 5–500 ký tự",
    reasonRule: "Nhập lý do 5–500 ký tự.",
    quantityRule: "Số nhận 0–999.",
    submit: "Lưu kết luận",
    done: "Đã sửa kết luận.",
  },
  generic: "Có lỗi hệ thống. Thử lại sau ít phút.",
};
