/** Chữ khối "Hàng hoàn" ở D4 + Dialog Gắn đơn / Sửa kết luận — nguyên văn 01 §10.5 D4 khi có (02b-admin §9). */
export const COPY = {
  section: {
    title: "Hàng hoàn",
    request: (sn: string) => `Yêu cầu ${sn}`,
    returnTracking: "Mã chiều về",
    reason: "Lý do",
    reported: "Sàn báo",
    due: "Hạn phản hồi",
    packages: (n: number) => `${n} kiện`,
    claims: "Hồ sơ khiếu nại",
    photos: "Ảnh",
    noInspection: "Chưa có kết quả kiểm.",
    mergedInto: (code: string) => `Đã gộp vào ${code}`,
  },
  inspection: {
    result: "Kết quả kiểm",
    operator: (name: string) => `Người kiểm ${name}`,
    product: "Sản phẩm",
    requested: "Yêu cầu",
    received: "Nhận",
    condition: "Tình trạng",
    reference: "Chỉ tham khảo",
    autoClosed: "Tự đóng",
    corrected: (n: number) => `Đã sửa ${n} lần`,
    history: "Lịch sử sửa kết luận",
    before: "Kết luận trước",
    reason: "Lý do",
    note: "Ghi chú",
    noLines: "Không có dòng sản phẩm.",
  },
  link: {
    open: "Gắn đơn",
    title: "Gắn đơn",
    code: "Mã đơn sàn hoặc mã vận đơn gốc",
    codeHint: "Nhập rồi bấm Tìm",
    min: "Nhập ít nhất 6 ký tự.",
    find: "Tìm",
    searching: "Đang tìm đơn",
    notFound: "Không tìm thấy đơn.",
    pick: "Chọn kiện",
    preview: "Đơn tìm được",
    order: (sn: string) => `Đơn ${sn}`,
    mergeInto: (code: string) => `Sẽ gộp vào ${code}`,
    submit: "Gắn đơn này",
    done: (sn: string) => `Đã gắn đơn ${sn}.`,
    mergedClaim: (from: string, into: string) => `Đã gộp ${from} vào ${into}`,
    alreadyReturned: "Đơn này đã có kiện hoàn được nhận.",
  },
  correct: {
    open: "Sửa kết luận",
    title: "Sửa kết luận",
    expired: "Đã quá 7 ngày, không sửa được.",
    applyAll: (n: number, code: string) => `Áp cho cả ${n} kiện của hồ sơ ${code}`,
    reference: "Đơn nhiều kiện — dòng sản phẩm chỉ tham khảo, chỉ sửa kết luận chung.",
    received: (name: string) => `Số nhận ${name}`,
    condition: (name: string) => `Tình trạng ${name}`,
    conclusion: "Kết luận",
    okLocked: "Có dòng thiếu / hỏng — không chọn Nguyên vẹn được.",
    note: "Ghi chú",
    noteRequired: "Nhập ghi chú khi chọn Khác.",
    noteMax: "Tối đa 500 ký tự.",
    reason: "Lý do sửa",
    reasonHint: "Bắt buộc, 5–500 ký tự",
    reasonRule: "Nhập lý do 5–500 ký tự.",
    quantityRule: "Số nhận 0–999.",
    submit: "Lưu kết luận",
    done: "Đã sửa kết luận.",
  },
  /** D14 — Hàng hoàn (01 §10.5 D14). */
  list: {
    title: "Hàng hoàn",
    subtitle: "Kiện hoàn đang về, quá hạn, đã nhận và yêu cầu chỉ hoàn tiền",
    tabs: "Nhóm hàng hoàn",
    caption: "Danh sách hồ sơ hàng hoàn",
    results: "Kết quả",
    q: "Mã vận đơn / mã đơn",
    search: "Tìm",
    kind: "Loại",
    any: "Tất cả",
    from: "Từ",
    to: "Đến",
    clear: "Xóa bộ lọc",
    loading: "Đang tải hàng hoàn",
    error: "Không tải được danh sách hàng hoàn.",
    retry: "Thử lại",
    rangeError: "Khoảng ngày không hợp lệ (tối đa 92 ngày).",
    empty: {
      EXPECTED: "Không có kiện hoàn nào đang về.",
      MISSING: "Không có kiện hoàn quá hạn.",
      RECEIVED: "Chưa có kiện hoàn nào đã nhận.",
      NO_PARCEL: "Không có yêu cầu chỉ hoàn tiền.",
      UNIDENTIFIED: "Không có kiện hoàn chưa xác định.",
      ALL: "Chưa có hồ sơ hàng hoàn.",
    },
    emptyFiltered: "Không có hồ sơ nào khớp bộ lọc.",
    col: {
      order: "Mã đơn",
      tracking: "Mã kiện / chiều về",
      kind: "Loại",
      reason: "Lý do",
      reported: "Sàn báo",
      waiting: "Chờ",
      status: "Trạng thái",
      conclusion: "Kết luận",
      claims: "Hồ sơ khiếu nại",
      actions: "Thao tác",
    },
    noOrder: "Chưa xác định",
    packages: (n: number) => `(${n} kiện)`,
    returnTracking: (code: string) => `Chiều về ${code}`,
    waitingDays: (n: number) => `${n} ngày`,
    createClaim: "Tạo hồ sơ khiếu nại",
    link: "Gắn đơn",
    open: (code: string) => `Mở chi tiết kiện ${code}`,
  },
  generic: "Có lỗi hệ thống. Thử lại sau ít phút.",
};
