/** Chữ hồ sơ khiếu nại (D4 Tạo hồ sơ, D16, D17, gói bằng chứng) — nguyên văn 01 §10.5 khi có (02b-admin §9). */
export const COPY = {
  create: {
    title: "Tạo hồ sơ khiếu nại",
    open: "Tạo hồ sơ khiếu nại",
    code: "Mã vận đơn hoặc mã đơn",
    codeHint: "Quét hoặc nhập mã của kiện cần khiếu nại",
    find: "Tìm",
    notFound: "Không tìm thấy kiện.",
    pickPackage: "Chọn kiện",
    type: "Loại",
    counterparty: "Bên nhận",
    note: "Ghi chú",
    noteHint: "Tối đa 1000 ký tự",
    noteMax: "Tối đa 1000 ký tự.",
    submit: "Tạo hồ sơ",
    created: (code: string) => `Đã tạo hồ sơ ${code}.`,
    /** BR-27 (01 §10.5 D4): "Kiện này đã có hồ sơ Hộp rỗng đang mở: KN-000124." */
    exists: (type: string, code: string) => `Kiện này đã có hồ sơ ${type} đang mở: ${code}.`,
    openExisting: "Mở hồ sơ",
    needPackage: "Chọn kiện trước khi tạo hồ sơ.",
  },
  list: {
    title: "Hồ sơ khiếu nại",
    subtitle: "Theo dõi hồ sơ khiếu nại gửi sàn / đơn vị vận chuyển và hạn gửi",
    create: "Tạo hồ sơ",
    tabs: "Trạng thái hồ sơ",
    all: "Tất cả",
    q: "Mã hồ sơ, mã vận đơn hoặc mã đơn",
    search: "Tìm",
    type: "Loại",
    counterparty: "Bên nhận",
    due: "Hạn",
    dueSoon: "Sắp hết hạn",
    overdue: "Quá hạn",
    mine: "Của tôi",
    any: "Tất cả",
    clear: "Xóa bộ lọc",
    empty: "Chưa có hồ sơ khiếu nại.",
    emptyFiltered: "Không có hồ sơ nào khớp bộ lọc.",
    error: "Không tải được danh sách hồ sơ.",
    retry: "Thử lại",
    caption: "Danh sách hồ sơ khiếu nại",
    results: "Kết quả",
    loading: "Đang tải",
  },
  col: {
    code: "Mã hồ sơ",
    package: "Mã kiện",
    /** item 03 (FR-07.01). */
    shop: "Sàn · Shop",
    type: "Loại",
    counterparty: "Bên nhận",
    status: "Trạng thái",
    owner: "Phụ trách",
    deadline: "Hạn",
    created: "Tạo lúc",
    source: "Nguồn",
  },
  noOwner: "(chưa có)",
  detail: {
    loading: "Đang tải hồ sơ",
    notFound: "Không tìm thấy hồ sơ.",
    back: "Về Hồ sơ khiếu nại",
    error: "Không tải được hồ sơ.",
    retry: "Thử lại",
    to: (counterparty: string) => `gửi ${counterparty}`,
    order: (sn: string) => `Đơn ${sn}`,
    package: "Kiện",
    returnCase: "Hàng hoàn",
    owner: "Phụ trách",
    take: "Nhận phụ trách",
    pickOwner: "Người phụ trách",
    saveOwner: "Giao",
    deadline: "Hạn",
    editDeadline: "Đổi hạn",
    newDeadline: "Hạn mới",
    saveDeadline: "Lưu hạn",
    saveRef: "Lưu mã",
    cancel: "Hủy",
    ref: "Mã tham chiếu sàn",
    refMax: "Tối đa 64 ký tự.",
    recovered: "Số tiền thu hồi",
    closeReason: "Lý do đóng",
    changeStatus: "Đổi trạng thái",
    stepper: "Tiến trình hồ sơ",
    closedNotice: "Hồ sơ đã đóng — chỉ xem, vẫn thêm ghi chú và xuất gói bằng chứng được.",
    updated: "Đã cập nhật hồ sơ.",
    /** 01 §10.5 D17 "Xung đột". */
    conflict: (who: string | null) => `Hồ sơ vừa được ${who ?? "người khác"} cập nhật. Đã tải lại.`,
    changedElsewhere: "Hồ sơ vừa được cập nhật.",
  },
  transition: {
    title: (label: string) => `Chuyển sang "${label}"`,
    submittedHint: "Nhập mã khiếu nại trên Seller Center. Gửi qua chat sàn thì ghi chú lại thay cho mã.",
    ref: "Mã tham chiếu sàn",
    refOrReason: "Nhập mã tham chiếu sàn hoặc ghi chú.",
    sentNote: "Ghi chú (khi không có mã)",
    amount: "Số tiền thu hồi (đ)",
    amountRule: "Nhập số tiền là số nguyên ≥ 0.",
    reason: "Lý do",
    reasonRule: "Nhập lý do 5–500 ký tự.",
    closeWarn:
      "Sau khi đóng, clip và ảnh trong hồ sơ được xóa theo thời hạn lưu thông thường tính từ hôm nay.",
    confirm: "Xác nhận",
  },
  evidence: {
    title: "Bằng chứng",
    pack: "Phiên đóng gói",
    return: "Phiên mở hoàn",
    play: (label: string) => `Xem ${label}`,
    remove: "Bỏ",
    add: "Thêm",
    addSession: "Thêm phiên",
    others: "Phiên khác của kiện:",
    photos: (n: number) => `Ảnh (${n})`,
    empty: "Hồ sơ chưa có bằng chứng.",
    auto: "Tự chọn",
    noPackClip: "Không có clip đóng gói",
    packClipDeleted: "Clip đóng gói đã bị xóa theo chính sách lưu trữ",
    returnClipPending: "Clip mở hoàn đang được cắt",
    clipDeleted: (date: string) => `Clip đã bị xóa ngày ${date}`,
    noClip: "Phiên không có clip",
    removeTitle: "Lý do bỏ",
    removeHint: "Bằng chứng do hệ thống tự chọn — ghi lý do bỏ (5–500 ký tự).",
    removeRule: "Nhập lý do 5–500 ký tự.",
    removeConfirm: "Bỏ bằng chứng",
    saved: "Đã cập nhật bằng chứng.",
    player: "Clip bằng chứng",
    // ---- item 03 (01 §10.5 D17 — BR-38, BR-39) ----
    primary: "Phiên chính",
    prior: (status: string) => `Phiên mở hoàn trước · ${status === "ABANDONED" ? "Bỏ dở" : "Đã hủy"}`,
    priorAlert: (n: number, list: string, primary: boolean) =>
      `Kiện có ${n} phiên mở hoàn trước (${list}) — đã đưa vào bằng chứng${primary ? ", là phiên chính" : ""}.`,
    priorItem: (status: string, at: string) => `${status === "ABANDONED" ? "bỏ dở" : "đã hủy"} ${at}`,
    excludedAlert: (n: number, times: string) =>
      `Kiện có ${n} phiên mở hoàn bị loại vì quét nhầm (${times}) — không đưa vào bằng chứng. Video vẫn được giữ; thêm tay nếu cần.`,
    addToEvidence: "Thêm vào bằng chứng",
    addToEvidenceAt: (at: string) => `Thêm vào bằng chứng phiên ${at}`,
    snapshot: (at: string) => `Ảnh ${at}`,
    removeDialogTitle: "Bỏ bằng chứng?",
    removeReason: "Lý do",
    removeReasonHint: "Bắt buộc, 5–500 ký tự",
    removeReasonRule: "Nhập lý do bỏ bằng chứng (5–500 ký tự).",
    keepSession: (date: string) =>
      `Clip và ảnh của phiên này được giữ tới ${date} rồi tự xóa (trừ khi thuộc hồ sơ khác).`,
    keepSnapshot: (date: string) => `Ảnh này được giữ tới ${date} rồi tự xóa (trừ khi thuộc hồ sơ khác).`,
    cancel: "Hủy",
    removedTitle: (n: number) => `Bằng chứng đã bỏ (${n})`,
    removedBy: (by: string, at: string) => `Bỏ bởi ${by} lúc ${at}`,
    removedReason: (reason: string) => `Lý do: ${reason}`,
    removedKeep: (date: string) => `Giữ tới ${date}`,
    restore: "Thêm lại",
    restoreFor: (label: string) => `Thêm lại ${label}`,
    systemUser: "Hệ thống",
    // ---- item 03 T-264 (01 §10.5 D17 v0.4 — API-189) ----
    rowMenu: (label: string) => `Thao tác ${label}`,
    markWrongScan: "Đánh dấu quét nhầm",
    unmark: "Bỏ đánh dấu",
    unmarkAt: (at: string) => `Bỏ đánh dấu phiên ${at}`,
    reviewAlert: (n: number) =>
      `Kiện có ${n} phiên mở hoàn do quản lý hủy trước khi hệ thống ghi lý do — đã đưa vào bằng chứng nhưng chưa làm phiên chính. Xem video rồi chọn.`,
    confirmReturn: "Là phiên hoàn thật",
    confirmReturnAt: (at: string) => `Là phiên hoàn thật (${at})`,
    /** v0.5 (DEC-529): chip phiên đã gỡ lý do hủy / đã xác nhận "Cần soát" (`session.return_confirmed`). */
    returnConfirmed: "Đã xác nhận phiên hoàn thật",
    wrongScanShort: "Quét nhầm",
    reviewActionsFor: (at: string) => `Phiên ${at}`,
  },
  /** API-189 dialogs (01 §10.5 D17). */
  review: {
    markTitle: "Đánh dấu phiên quét nhầm?",
    unmarkTitle: "Bỏ đánh dấu quét nhầm?",
    confirmTitle: "Xác nhận là phiên hoàn thật?",
    /** v0.5 (DEC-529): gỡ lý do hủy "Quét nhầm" / "Không phải hàng hoàn" — ADMIN / SUPERVISOR. */
    overrideTitle: "Gỡ lý do hủy, xác nhận là phiên hoàn thật?",
    overrideText:
      "Phiên sẽ vào bằng chứng của hồ sơ này và có thể thành phiên chính. Lý do hủy cũ vẫn lưu trong nhật ký.",
    overridden: "Đã xác nhận phiên hoàn thật.",
    reason: "Lý do*",
    reasonRequired: "Chọn lý do.",
    note: "Ghi chú*",
    noteHint: "5–500 ký tự",
    noteRule: "Nhập ghi chú (5–500 ký tự).",
    markText: (date: string) =>
      `Phiên sẽ bị bỏ khỏi bằng chứng của mọi hồ sơ chưa đóng và không được tự chọn lại. Video vẫn được giữ tới ${date} (trừ khi thuộc hồ sơ khác).`,
    unmarkText: "Phiên không tự vào lại bằng chứng — thêm tay nếu cần.",
    confirmText: "Phiên sẽ được tính như phiên mở hoàn thường và có thể thành phiên chính.",
    mark: "Đánh dấu",
    unmarkConfirm: "Bỏ đánh dấu",
    confirm: "Xác nhận",
    cancel: "Hủy",
    marked: "Đã đánh dấu phiên quét nhầm.",
    unmarked: "Đã bỏ đánh dấu.",
    confirmed: "Đã xác nhận.",
  },
  /** `AffectedSharesDialog` (01 §10.5 D17 v0.5 — DEC-531): phiên vừa đánh dấu quét nhầm còn trong link chia sẻ. */
  affected: {
    title: (n: number) => `Phiên này đang có trong ${n} link chia sẻ còn hiệu lực`,
    text: "Người nhận vẫn xem được video phiên này tới khi thu hồi hoặc hết hạn.",
    expires: (at: string) => `hết hạn ${at}`,
    revoke: "Thu hồi link",
    revokeFor: (r: string) => `Thu hồi link gửi ${r}`,
    askAdmin: "Nhờ Admin / Supervisor thu hồi",
    /** mới (DEC-721) — dòng đã thu hồi trong dialog. */
    revoked: "Đã thu hồi",
    /** mới (DEC-721) — người tạo link. */
    createdBy: (who: string) => `Tạo bởi ${who}`,
    close: "Đóng",
  },
  pack: {
    open: "Xuất gói bằng chứng",
    title: "Xuất gói bằng chứng",
    /** 01 §10.5 D17: "Gói gồm: clip gốc, video ghép có chữ cho 2 phiên chính, 4 ảnh, file thông tin." */
    contents: (sessions: number, photos: number) =>
      `Gói gồm: clip gốc, video ghép có chữ cho ${sessions} phiên chính, ${photos} ảnh, file thông tin.`,
    create: "Tạo gói",
    progress: "Đang tạo gói bằng chứng",
    ready: "Gói bằng chứng đã sẵn sàng.",
    download: "Tải gói bằng chứng (.zip)",
    size: "Dung lượng",
    keepUntil: "File giữ tới",
    linkNote: "Liên kết tải có hạn 10 phút — bấm Tải để lấy liên kết mới.",
    missing: "Phần thiếu trong gói:",
    failed: "Không tạo được gói bằng chứng. Bấm Thử lại; nếu vẫn lỗi, báo Admin kèm mã hồ sơ.",
    retry: "Thử lại",
    noEvidence: "Hồ sơ chưa có bằng chứng.",
    gone: "Gói không còn (quá 24 giờ hoặc do tài khoản khác tạo). Bấm Tạo gói để tạo lại.",
    inProgressOther: "Hồ sơ đang có gói bằng chứng do người khác tạo. Thử lại sau ít phút.",
    camera: (role: string, at: string) => `${role} phiên ${at}`,
    missingReason: {
      CLIP_DELETED: "clip đã bị xóa",
      CLIP_MISSING: "không có clip",
      CLIP_NOT_READY: "clip chưa cắt xong",
      CLIP_FAILED: "clip cắt lỗi",
      CLIP_FILE_MISSING: "mất file clip",
      CLIP_CHECKSUM_MISMATCH: "SHA-256 không khớp",
      SNAPSHOT_DELETED: "ảnh đã bị xóa",
    } as Record<string, string>,
  },
  notes: {
    title: "Ghi chú",
    system: "Hệ thống",
    add: "Thêm ghi chú",
    send: "Gửi",
    rule: "Nhập ghi chú 1–1000 ký tự.",
    empty: "Chưa có ghi chú.",
  },
  generic: "Có lỗi hệ thống. Thử lại sau ít phút.",
};
