/** Chữ hồ sơ khiếu nại (D4 Tạo hồ sơ, D16, D17, gói bằng chứng) — nguyên văn 01 §10.5 khi có (02b-admin §9). */
export const COPY = {
  create: {
    title: "Tạo hồ sơ khiếu nại",
    open: "Tạo hồ sơ khiếu nại",
    code: "Mã vận đơn hoặc mã đơn",
    codeHint: "Quét hoặc nhập mã của kiện cần khiếu nại",
    find: "Tìm",
    notFound: "Không tìm thấy kiện.",
    pickPackage: "Chọn kiện",
    type: "Loại",
    counterparty: "Bên nhận",
    note: "Ghi chú",
    noteHint: "Tối đa 1000 ký tự",
    noteMax: "Tối đa 1000 ký tự.",
    submit: "Tạo hồ sơ",
    created: (code: string) => `Đã tạo hồ sơ ${code}.`,
    /** BR-27 (01 §10.5 D4): "Kiện này đã có hồ sơ Hộp rỗng đang mở: KN-000124." */
    exists: (type: string, code: string) => `Kiện này đã có hồ sơ ${type} đang mở: ${code}.`,
    openExisting: "Mở hồ sơ",
    needPackage: "Chọn kiện trước khi tạo hồ sơ.",
  },
  list: {
    title: "Hồ sơ khiếu nại",
    subtitle: "Theo dõi hồ sơ khiếu nại gửi sàn / đơn vị vận chuyển và hạn gửi",
    create: "Tạo hồ sơ",
    tabs: "Trạng thái hồ sơ",
    all: "Tất cả",
    q: "Mã hồ sơ, mã vận đơn hoặc mã đơn",
    search: "Tìm",
    type: "Loại",
    counterparty: "Bên nhận",
    due: "Hạn",
    dueSoon: "Sắp hết hạn",
    overdue: "Quá hạn",
    mine: "Của tôi",
    any: "Tất cả",
    clear: "Xóa bộ lọc",
    empty: "Chưa có hồ sơ khiếu nại.",
    emptyFiltered: "Không có hồ sơ nào khớp bộ lọc.",
    error: "Không tải được danh sách hồ sơ.",
    retry: "Thử lại",
    caption: "Danh sách hồ sơ khiếu nại",
    results: "Kết quả",
    loading: "Đang tải",
  },
  col: {
    code: "Mã hồ sơ",
    package: "Mã kiện",
    type: "Loại",
    counterparty: "Bên nhận",
    status: "Trạng thái",
    owner: "Phụ trách",
    deadline: "Hạn",
    created: "Tạo lúc",
    source: "Nguồn",
  },
  noOwner: "(chưa có)",
  detail: {
    loading: "Đang tải hồ sơ",
    notFound: "Không tìm thấy hồ sơ.",
    back: "Về Hồ sơ khiếu nại",
    error: "Không tải được hồ sơ.",
    retry: "Thử lại",
    to: (counterparty: string) => `gửi ${counterparty}`,
    order: (sn: string) => `Đơn ${sn}`,
    package: "Kiện",
    returnCase: "Hàng hoàn",
    owner: "Phụ trách",
    take: "Nhận phụ trách",
    pickOwner: "Người phụ trách",
    saveOwner: "Giao",
    deadline: "Hạn",
    editDeadline: "Đổi hạn",
    newDeadline: "Hạn mới",
    saveDeadline: "Lưu hạn",
    saveRef: "Lưu mã",
    cancel: "Hủy",
    ref: "Mã tham chiếu sàn",
    refMax: "Tối đa 64 ký tự.",
    recovered: "Số tiền thu hồi",
    closeReason: "Lý do đóng",
    changeStatus: "Đổi trạng thái",
    stepper: "Tiến trình hồ sơ",
    closedNotice: "Hồ sơ đã đóng — chỉ xem, vẫn thêm ghi chú và xuất gói bằng chứng được.",
    updated: "Đã cập nhật hồ sơ.",
    /** 01 §10.5 D17 "Xung đột". */
    conflict: (who: string | null) => `Hồ sơ vừa được ${who ?? "người khác"} cập nhật. Đã tải lại.`,
    changedElsewhere: "Hồ sơ vừa được cập nhật.",
  },
  transition: {
    title: (label: string) => `Chuyển sang "${label}"`,
    submittedHint: "Nhập mã khiếu nại trên Seller Center. Gửi qua chat sàn thì ghi chú lại thay cho mã.",
    ref: "Mã tham chiếu sàn",
    refOrReason: "Nhập mã tham chiếu sàn hoặc ghi chú.",
    sentNote: "Ghi chú (khi không có mã)",
    amount: "Số tiền thu hồi (đ)",
    amountRule: "Nhập số tiền là số nguyên ≥ 0.",
    reason: "Lý do",
    reasonRule: "Nhập lý do 5–500 ký tự.",
    closeWarn:
      "Sau khi đóng, clip và ảnh trong hồ sơ được xóa theo thời hạn lưu thông thường tính từ hôm nay.",
    confirm: "Xác nhận",
  },
  evidence: {
    title: "Bằng chứng",
    pack: "Phiên đóng gói",
    return: "Phiên mở hoàn",
    play: (label: string) => `Xem ${label}`,
    remove: "Bỏ",
    add: "Thêm",
    addSession: "Thêm phiên",
    others: "Phiên khác của kiện:",
    photos: (n: number) => `Ảnh (${n})`,
    empty: "Hồ sơ chưa có bằng chứng.",
    auto: "Tự chọn",
    noPackClip: "Không có clip đóng gói",
    packClipDeleted: "Clip đóng gói đã bị xóa theo chính sách lưu trữ",
    returnClipPending: "Clip mở hoàn đang được cắt",
    clipDeleted: (date: string) => `Clip đã bị xóa ngày ${date}`,
    noClip: "Phiên không có clip",
    removeTitle: "Lý do bỏ",
    removeHint: "Bằng chứng do hệ thống tự chọn — ghi lý do bỏ (5–500 ký tự).",
    removeRule: "Nhập lý do 5–500 ký tự.",
    removeConfirm: "Bỏ bằng chứng",
    saved: "Đã cập nhật bằng chứng.",
    player: "Clip bằng chứng",
  },
  notes: {
    title: "Ghi chú",
    system: "Hệ thống",
    add: "Thêm ghi chú",
    send: "Gửi",
    rule: "Nhập ghi chú 1–1000 ký tự.",
    empty: "Chưa có ghi chú.",
  },
  generic: "Có lỗi hệ thống. Thử lại sau ít phút.",
};
